# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: プロジェクト
    url: projects
    weight: 40
  - name: チーム
    url: team
    weight: 30
  - name: 研究業績
    url: publications
    weight: 50
  - name: お問合せ
    url: /#contact
    weight: 70
